# Generated by theme-set-templates — do not edit directly
$lock_fg = rgba({{ foreground_rgb }}, 1.0)
$lock_fg_dim = rgba({{ color8_rgb }}, 1.0)
$lock_accent = rgba({{ accent_rgb }}, 1.0)
$lock_input_bg = rgba({{ color0_rgb }}, 0.6)
$lock_input_border = rgba({{ accent_rgb }}, 0.4)
