/**
 * Generated by theme-set-templates — do not edit directly
 **/

* {
    background:     {{ background }}FF;
    background-alt: {{ color0 }}FF;
    foreground:     {{ foreground }}FF;
    selected:       {{ accent }}FF;
    active:         {{ color2 }}FF;
    urgent:         {{ color1 }}FF;
}
