# Generated by theme-set-templates — do not edit directly
nord0 = '{{ background }}'
nord1 = '{{ color0 }}'
nord2 = '{{ color8 }}'
nord3 = '{{ color8 }}'
nord4 = '{{ foreground }}'
nord11 = '{{ color1 }}'
nord13 = '{{ color3 }}'
nord14 = '{{ color2 }}'
